{
 "title": "JAVA Overview",
 "description": "Dashboard for JVM metrics with Prometheus / JMX Exporter",
 "tags": [
  "JVM",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(kube_pod_info{namespace=\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "老年代GC次数统计",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{kubernetes_pod_name=~\"$pod\", gc=\"PS MarkSweep\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "老年代GC时间统计（ms）",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_sum{kubernetes_pod_name=~\"$pod\",gc=\"PS Scavenge\"} * 1000",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "年轻代GC次数统计",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{kubernetes_pod_name=~\"$pod\", gc=\"PS Scavenge\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "年轻代GC时间统计（ms）",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_sum{kubernetes_pod_name=~\"$pod\", gc=\"PS Scavenge\"} * 1000",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "状态",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{kubernetes_pod_name=~\"$pod\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "容器", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU使用量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", pod_name=\"$pod\", container_name!=\"POD\"}) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "内存使用量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\", pod_name=\"$pod\", container_name!=\"POD\", container_name!=\"\"}) by (container_name)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{pod_name}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "网络IO",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{pod_name=\"$pod\"}[1m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "receive",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "- sum(irate(container_network_transmit_bytes_total{pod_name=\"$pod\"}[1m]))",
     "legendFormat": "transmit"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "JVM堆内存",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{kubernetes_pod_name=~\"$pod\", area=\"heap\"}",
     "legendFormat": "{{area}} memory"
    }
   ]
  },
  {
   "title": "JVM 内存使用率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{kubernetes_pod_name=~\"$pod\",pool=\"PS Eden Space\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Eden Space Max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "jvm_memory_pool_bytes_used{kubernetes_pod_name=~\"$pod\",pool=\"PS Eden Space\"}",
     "legendFormat": "Eden Space Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_max{kubernetes_pod_name=~\"$pod\",pool=\"PS Old Gen\"}",
     "legendFormat": "Old Gen Max"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{kubernetes_pod_name=~\"$pod\",pool=\"PS Old Gen\"}",
     "legendFormat": "Old Gen Used"
    }
   ]
  },
  {
   "title": "JVM线程",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_peak{kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "线程峰值"
    },
    {
     "expr": "jvm_threads_current{kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "当前线程数"
    },
    {
     "expr": "jvm_threads_daemon{kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "守护线程数"
    },
    {
     "expr": "jvm_threads_deadlocked{kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "死锁线程数"
    }
   ]
  },
  {
   "title": "Tomcat Servlet请求次数/分钟",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(tomcat_servlet_requestcount_total{kubernetes_pod_name=\"$pod\"}[1m])",
     "legendFormat": "{{module}}/{{servlet}}"
    }
   ]
  },
  {
   "title": "JVM GC 时间/分钟",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{kubernetes_pod_name=~\"$pod\"}[1m])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "JVM类加载",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded{kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "loaded"
    }
   ]
  }
 ]
}