{
 "title": "OCP Cluster Summary Copy",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API Server request count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_count[2m])) by (verb)",
     "legendFormat": "{{ verb }} "
    },
    {
     "expr": "sum(rate(apiserver_request_count[2m]))",
     "legendFormat": "总请求数"
    }
   ]
  },
  {
   "title": "API Server requests latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_latencies_count[5m])) by (verb)",
     "legendFormat": "{{ verb }}"
    },
    {
     "expr": "max(sum(rate(apiserver_request_latencies_count[5m])) by (verb))",
     "legendFormat": "最大延迟"
    }
   ]
  },
  {
   "title": "Kube-controller e2e scheduling latency",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "irate(scheduler_e2e_scheduling_latency_microseconds_sum[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Kube-controller algorithm latency",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "irate(scheduler_scheduling_algorithm_latency_microseconds_sum[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Etcd has a leader?",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 19 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "max(etcd_server_has_leader)" }
   ]
  },
  {
   "title": "Etcd dbSize",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 3, "y": 19 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "etcd_debugging_mvcc_db_total_size_in_bytes{instance=\"192.168.3.132:2379\"}"
    }
   ]
  },
  {
   "title": "The number of leader changes seen",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 19 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(etcd_server_leader_changes_seen_total)"
    }
   ]
  },
  {
   "title": "Disk Sync Duration",
   "type": "graph",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket[5m])) by (instance, le))",
     "legendFormat": "{{instance}} WAL fsync"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket[5m])) by (instance, le))",
     "legendFormat": "{{instance}} DB fsync"
    }
   ]
  },
  {
   "title": "Client Traffic In",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_received_bytes_total{job=\"etcd\"}[5m])",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "Client Traffic Out",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_received_bytes_total{job=\"etcd\"}[5m])",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "Peer Traffic In",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_network_peer_received_bytes_total[5m])) by (instance)",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "Peer Traffic Out",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_network_peer_sent_bytes_total[5m])) by (instance)",
     "legendFormat": "{{instance}} Peer Traffic Out"
    }
   ]
  },
  {
   "title": "Snapshot duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(etcd_disk_backend_snapshot_duration_seconds_sum{job=\"etcd\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disks operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_disk_wal_fsync_duration_seconds_sum{job=\"etcd\"}[5m]))",
     "legendFormat": "\tThe latency distributions of fsync called by wal"
    },
    {
     "expr": "sum(rate(etcd_disk_backend_commit_duration_seconds_sum{job=\"etcd\"}[5m]))",
     "legendFormat": "The latency distributions of commit called by backend"
    }
   ]
  },
  {
   "title": "Running master API",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 42 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"kube-system\",phase=\"Running\",pod=~\"master-api.*\"})"
    }
   ]
  },
  {
   "title": "Master API Pod CPU core used",
   "type": "graph",
   "gridPos": { "h": 4, "w": 20, "x": 4, "y": 42 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"kube-system\",pod_name=~\"master-api.*\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Running master controller",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 46 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"kube-system\",phase=\"Running\",pod=~\"master-controller.*\"})"
    }
   ]
  },
  {
   "title": "Master Controller Pod CPU core used",
   "type": "graph",
   "gridPos": { "h": 4, "w": 20, "x": 4, "y": 46 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"kube-system\",pod_name=~\"master-controller.*\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Running master etcd",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 50 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"kube-system\",phase=\"Running\",pod=~\"master-etcd.*\"})"
    }
   ]
  },
  {
   "title": "Master Etcd Pod CPU core used",
   "type": "graph",
   "gridPos": { "h": 4, "w": 20, "x": 4, "y": 50 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"kube-system\",pod_name=~\"master-etcd.*\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "master-10.41.3.11 1分钟负载",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 54 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load1{instance=~\"10.41.3.11.*\"}"
    }
   ]
  },
  {
   "title": "master-10.41.3.12 1分钟负载",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 54 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load1{instance=~\"10.41.3.12.*\"}"
    }
   ]
  },
  {
   "title": "master-10.41.3.13 1分钟负载",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 54 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load1{instance=~\"10.41.3.13.*\"}"
    }
   ]
  },
  {
   "title": "Master Server 1分钟负载",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"^10.41.3.11.*|^10.41.3.12.*|^10.41.3.13.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "master-10.41.3.11 5分钟负载",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 58 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load5{instance=~\"10.41.3.11.*\"}"
    }
   ]
  },
  {
   "title": "master-10.41.3.12 5分钟负载",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 58 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load5{instance=~\"10.41.3.12.*\"}"
    }
   ]
  },
  {
   "title": "master-10.41.3.13 5分钟负载",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 58 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load5{instance=~\"10.41.3.13.*\"}"
    }
   ]
  },
  {
   "title": "Master Server 5分钟负载",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load5{instance=~\"^10.41.3.11.*|^10.41.3.12.*|^10.41.3.13.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Master API Pod Memory used",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"kube-system\",container_name=\"api\",pod_name=~\"master-api-.*\",container_name!=\"POD\"} / 263526520",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Master controllers Pod Memory used",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"kube-system\",container_name=\"controllers\",pod_name=~\"master-controllers-.*\",container_name!=\"POD\"} / 263526520",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Master etcd Pod Memory used",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"kube-system\",container_name=\"etcd\",pod_name=~\"master-etcd-.*\",container_name!=\"POD\"} / 263526520",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Master Pods 入口网络流量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate (container_network_receive_bytes_total{pod_name=~\"^master.*\",namespace=\"kube-system\"}[5m])) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "sum(irate (container_network_receive_bytes_total{pod_name=~\"^master.*\",namespace=\"kube-system\"}[5m]))",
     "legendFormat": "入口总和"
    }
   ]
  },
  {
   "title": "Master Pods 出口网络流量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate (container_network_transmit_bytes_total{pod_name=~\"^master.*\",namespace=\"kube-system\"}[5m])) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "sum(irate (container_network_transmit_bytes_total{pod_name=~\"^master.*\",namespace=\"kube-system\"}[5m]))",
     "legendFormat": "出口总和"
    }
   ]
  }
 ]
}