{
 "title": "OpenShift Router",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Router实例",
    "query": "label_values(haproxy_up, instance)"
   },
   {
    "name": "port",
    "query": "label_values(haproxy_up, instance)"
   },
   {
    "name": "frontend",
    "label": "Frontend",
    "query": "label_values(haproxy_frontend_bytes_in_total{instance=~\"$host:$port\"}, frontend)"
   },
   {
    "name": "route",
    "label": "Route",
    "query": "label_values(haproxy_backend_up{instance=~\"$host:$port\"}, route)"
   },
   {
    "name": "server",
    "label": "Server",
    "query": "label_values(haproxy_server_bytes_in_total{instance=~\"$host:$port\", route=~\"$backend\"}, server)"
   },
   {
    "name": "code",
    "label": "Code",
    "query": "label_values(haproxy_server_http_responses_total{instance=~\"$host:$port\", server=~\"$server\"}, code)"
   }
  ]
 },
 "panels": [
  {
   "title": "Router实例的状态",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(haproxy_up{instance=~\"$host:$port\"})"
    }
   ]
  },
  {
   "title": "Backends服务",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(haproxy_backend_up{instance=~\"$host:$port\"})",
     "legendFormat": "Backends Up"
    }
   ]
  },
  {
   "title": "监控服务启动时间(小时)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(time() - haproxy_process_start_time_seconds{instance=~\"$host:$port\"}) / 3600"
    }
   ]
  },
  {
   "title": "Router实例状态",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "haproxy_process_resident_memory_bytes{job=\"router\"}"
    }
   ]
  },
  {
   "title": "Router Cores Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum (irate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",pod_name=~\"^router-.*\"}[2m])) by (container_name, pod_name)",
     "legendFormat": "pod: {{ pod_name }} | {{ container_name }}"
    }
   ]
  },
  {
   "title": "后端服务健康检测失败统计",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(haproxy_server_connection_errors_total{route=~\"$route\",instance=\"$host:$port\"}[5m])",
     "legendFormat": "{{exported_service}}"
    }
   ]
  },
  {
   "title": "后端服务实例响应延时(最后1024个请求)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_http_average_response_latency_milliseconds{route=~\"$route\",instance=\"$host:$port\"}",
     "legendFormat": "response latency {{server}}"
    }
   ]
  },
  {
   "title": "Frontend状态码统计",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(haproxy_frontend_http_responses_total{frontend=~\"fe_no_sni|fe_sni|public|public_ssl\",instance=~\"192.168.0.55:1936\"}[5m])) by (code)",
     "legendFormat": "Frontend {{ code }}"
    }
   ]
  },
  {
   "title": "Frontend流量统计",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(haproxy_frontend_bytes_in_total{frontend=~\"$frontend\",instance=~\"$host:$port\"}[5m])) by (instance)",
     "legendFormat": "Frontend In"
    },
    {
     "expr": "sum(irate(haproxy_frontend_bytes_out_total{frontend=~\"$frontend\",instance=~\"$host:$port\"}[5m])) by (instance)",
     "legendFormat": "Frontend Out"
    }
   ]
  },
  {
   "title": "Frontend当前会话数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(haproxy_frontend_current_sessions{instance=~\"$host:$port\"}) by (instance)",
     "legendFormat": "{{ frontend }} Sessions"
    }
   ]
  },
  {
   "title": "后端服务当前会话数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(haproxy_server_current_sessions{route=~\"$route\",instance=~\"$host:$port\"}) by (instance)",
     "legendFormat": "Backend Sessions"
    }
   ]
  },
  {
   "title": "Frontend连接速率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_frontend_connections_total{instance=~\"$host:$port\"}[5m])",
     "legendFormat": "{{ frontend }} Connections"
    }
   ]
  },
  {
   "title": "后端服务连接状态",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(haproxy_backend_connections_total{route=~\"$route\",instance=~\"$host:$port\"}[5m])) by (instance)",
     "legendFormat": "Backend Connections"
    }
   ]
  }
 ]
}